### ISSUE TITLE
Script "miller_rabin_generate_primes.py" takes too long to execute.

### ISSUE THREAD

**Issue by tmyridis** [juli-dev1/Cryptography-fundamentals#1]
As I can see you are trying to generate two safe primes using Miller-Rabin implementation. I tried running the script but I got no answer in about 3 hours. I think you can use a different implementation of the powmod function. I can try and find a faster approach and see the time results.

**Comment by juli-dev1** [comment]
Sure go ahead if you can find something good. I tried fixing it too but I didnt find anything efficient.

**Comment by tmyridis** [comment]
Okay I am going to open a pull request when I find a fix.
